/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface FloatingMenu {
    'color': string;
  }
}

declare global {


  interface HTMLFloatingMenuElement extends Components.FloatingMenu, HTMLStencilElement {}
  var HTMLFloatingMenuElement: {
    prototype: HTMLFloatingMenuElement;
    new (): HTMLFloatingMenuElement;
  };
  interface HTMLElementTagNameMap {
    'floating-menu': HTMLFloatingMenuElement;
  }
}

declare namespace LocalJSX {
  interface FloatingMenu extends JSXBase.HTMLAttributes<HTMLFloatingMenuElement> {
    'color'?: string;
  }

  interface IntrinsicElements {
    'floating-menu': FloatingMenu;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements extends LocalJSX.IntrinsicElements {}
  }
}


